# cloudbuild.yaml
# Pipeline: build -> push -> deploy -> 

substitutions:
  _ARTIFACT_REPO: "devsecops-repo"    
  _REGION: "us-central1"              
  _PROJECT_ID: "my-gcp-project"       #trocar quando subir o projeto

steps:
  # 1. Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/devsecops-app:$SHORT_SHA'
      - '.'

  # 2. Push da imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/devsecops-app:$SHORT_SHA'

  # 3. Atualizar a imagem do Deployment no GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Obter credenciais do cluster
        gcloud container clusters get-credentials devsecops-cluster --region ${_REGION} --project ${_PROJECT_ID}
        # Atualizar imagem no deployment
        kubectl set image deployment/devsecops-app devsecops-app=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/devsecops-app:$SHORT_SHA --record

  # 4. SAST com Semgrep
  - name: 'returntocorp/semgrep:latest'
    id: 'semgrep'
    entrypoint: 'semgrep'
    args:
      - '--config'
      - 'auto'
      - '.'
    waitFor:
      - 'push'

  # 5. SCA com OWASP Dependency-Check (gera relatório)
  - name: 'owasp/dependency-check'
    id: 'dependency-check'
    args:
      - '--scan'
      - '.'
      - '--format'
      - 'ALL'
    waitFor:
      - 'push'

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/devsecops-app:$SHORT_SHA'
