# cloudbuild.yaml
# Pipeline completo: build -> push -> segurança -> deploy -> teste dinâmico

substitutions:
  _ARTIFACT_REPO: "devsecops-repo"
  _REGION: "us-central1"
  _PROJECT_ID: "infra-sd-host"
  _CLUSTER_NAME: "devsecops-cluster"
  _APP_NAME: "dvwa-app"
  _DEPLOYMENT_NAME: "dvwa-app"
  _REPORT_BUCKET: "gs://devsecops-reports-dvwa"
  _LOGS_BUCKET: "gs://infra-sd-host-cloudbuild-logs"
  _SOURCE_IMAGE: "vulnerables/web-dvwa:latest"

steps:
  # 0 Criar diretório de relatórios
  - name: 'ubuntu'
    id: 'setup'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /workspace/reports/dependency-check
        echo "Diretório de relatórios criado"

  # 1 Pull da imagem DVWA pública
  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-dvwa'
    args:
      - 'pull'
      - '${_SOURCE_IMAGE}'
    waitFor: ['setup']

  # 2 Tag e push da imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-dvwa'
    args:
      - 'tag'
      - '${_SOURCE_IMAGE}'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA'
    waitFor: ['pull-dvwa']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA'
    waitFor: ['push-dvwa']
    
  # 3 SAST com Semgrep (análise estática)
  - name: 'returntocorp/semgrep:latest'
    id: 'semgrep'
    entrypoint: 'semgrep'
    args:
      - '--config'
      - 'auto'
      - '--json'
      - '--output'
      - '/workspace/reports/semgrep-report.json'
      - '.'
    waitFor:
      - 'push'

  # 4 SCA - Análise de Composição de Software

  # NOTA: OWASP Dependency-Check comentado pois sem NVD API Key o download
  # da base de vulnerabilidades leva várias horas, inviabilizando o pipeline.
  # Para usar, obtenha uma API key gratuita em: https://nvd.nist.gov/developers/request-an-api-key
  # e adicione o argumento: '--nvdApiKey', '${_NVD_API_KEY}'
  #
  # - name: 'owasp/dependency-check'
  #   id: 'dependency-check'
  #   args:
  #     - '--scan'
  #     - '.'
  #     - '--format'
  #     - 'ALL'
  #     - '--out'
  #     - '/workspace/reports/dependency-check'
  #   waitFor:
  #     - 'push'
  
  # Alternativa: Trivy FS para SCA (mais rápido, usa base própria)
  - name: 'aquasec/trivy'
    id: 'sca-scan'
    args:
      - 'fs'
      - '--format'
      - 'json'
      - '--output'
      - '/workspace/reports/trivy-sca-report.json'
      - '.'
    waitFor:
      - 'push'

  # 5 IaC Scan (Terraform) com Checkov
  - name: 'bridgecrew/checkov:latest'
    id: 'checkov'
    args:
      - '-d'
      - './infra'
      - '-o'
      - 'json'
      - '--output-file-path'
      - '/workspace/reports/checkov-report.json'
    waitFor:
      - 'push'

  # 6 Container Scan (Trivy)
  - name: 'aquasec/trivy'
    id: 'trivy'
    args:
      - 'image'
      - '--format'
      - 'json'
      - '--output'
      - '/workspace/reports/trivy-report.json'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA'
    waitFor:
      - 'push'

  # 6.1 Deploy do MySQL no GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-mysql'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_REGION} --project ${_PROJECT_ID}
        kubectl apply -f Instrumentos/Codigos/DevSecOps/dvwa/k8s/mysql.yaml
        echo "Aguardando o MySQL iniciar..."
        sleep 30
    waitFor:
      - 'trivy'


  # 7 Deploy no GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_REGION} --project ${_PROJECT_ID}
        # Substituir placeholder da imagem no YAML
        sed -i "s|us-central1-docker.pkg.dev/PROJECT_ID/artifact-repo/dvwa-app:latest|${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA|g" Instrumentos/Codigos/DevSecOps/dvwa/k8s/dvwa.yaml
        # Aplicar o deployment
        kubectl apply -f Instrumentos/Codigos/DevSecOps/dvwa/k8s/dvwa.yaml
        echo "Aguardando pods ficarem prontos..."
        kubectl rollout status deployment/${_DEPLOYMENT_NAME} --timeout=120s
    waitFor:
      - 'deploy-mysql'

  # 8 DAST com OWASP ZAP (testes dinâmicos de segurança)
  # NOTA: A imagem mudou de owasp/zap2docker-stable para ghcr.io/zaproxy/zaproxy
  - name: 'ghcr.io/zaproxy/zaproxy:stable'
    id: 'zap-scan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Aguardar app ficar disponível
        echo "Aguardando DVWA ficar disponível..."
        sleep 60
        # Executar scan baseline do ZAP
        zap-baseline.py -t http://dvwa-service.default.svc.cluster.local:80 -r /workspace/reports/zap-report.html -J /workspace/reports/zap-report.json || true
    waitFor:
      - 'deploy'

  # 9 Upload dos relatórios de segurança para bucket GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'upload-reports'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Relatórios gerados ==="
        ls -la /workspace/reports/
        if [ -d "/workspace/reports" ]; then
          gsutil -m cp -r /workspace/reports/* ${_REPORT_BUCKET}/$BUILD_ID/
          echo "Relatórios salvos em: ${_REPORT_BUCKET}/$BUILD_ID/"
        else
          echo "Nenhum relatório gerado."
        fi
    waitFor:
      - 'zap-scan'
      - 'semgrep'
      - 'sca-scan'
      - 'checkov'
      - 'trivy'

  # 10 Exibir IP externo do DVWA
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'get-service-ip'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_REGION} --project ${_PROJECT_ID}
        kubectl get svc dvwa-service -o wide
    waitFor:
      - 'deploy'


images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA'

artifacts:
  objects:
    location: '${_REPORT_BUCKET}/$BUILD_ID/'
    paths:
      - '/workspace/reports/*'

options:
  dynamicSubstitutions: true
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
